[package]
name = "clio-slack-connector"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "clio-slack-connector"
path = "src/main.rs"

[dependencies]
tokio = { workspace = true }
shared = { path = "../../shared" }